name: example
description: Example application for Flutter blue plus Windows
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  flutter_blue_plus: ^1.31.3
#  flutter_blue_plus_windows:
#    path: ../

dev_dependencies:
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true
