name: example
description: Example application for Flutter blue plus Windows
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

  flutter_blue_plus_windows:
    path: ../

flutter:
  uses-material-design: true
