name: flutter_blue_plus_windows
description: Flutter blue plus for Windows
version: 1.16.0
repository: https://github.com/chan150/flutter_blue_plus_windows

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_blue_plus: any
  win_ble_plus : any
  stream_with_value: any
