name: flutter_blue_plus_windows
description: Flutter blue plus for Windows
version: 1.14.0
repository: https://github.com/chan150/flutter_blue_plus_windows

environment:
  sdk: ">=3.0.0 <4.0.0"

platform:
  windows:

dependencies:
  flutter_blue_plus: ^1.31.3
  win_ble:
    path: win_ble
  stream_with_value: ^0.5.0
  rxdart: ^0.27.7
