name: flutter_blue_plus_windows
description: Flutter blue plus for Windows
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_blue_plus: ^1.14.11
  win_ble: ^1.0.1

dev_dependencies:
  test: ^1.24.6

